"""
QRU FACTORY™ — Enterprise Department Registry (Treasure Standard™).

Single source of truth for the QRU Enterprise Operations Manual. Every menu item is
a Department that answers ONE clear Primary Question. No department exists simply
because it is a feature — each one earns its place by passing the One Question Test™.

This module is consumed by:
  - The navigation layer (tooltips / help text show the Primary Question)
  - The Enterprise Blueprint™ page (renders full Department Profiles)
  - Onboarding, documentation, and future AI-agent training

Standard profile fields (Treasure Standard™):
  name, route, section, mission, purpose, question, why_exists, problems_solved,
  responsibilities, inputs, outputs, daily_activities, ai_agents, people, related,
  workflow, use_cases, kpis, treasure_standard, future
"""

DEPARTMENTS = [
    # ───────────────────────── THE QRU EXPERIENCE ─────────────────────────
    {
        "key": "teach",
        "name": "QRU Digital Production Line™",
        "route": "/teach",
        "section": "The QRU Experience",
        "mission": "Turn a single teaching goal into a finished, verified learning product with one command.",
        "purpose": "Give the Founder and staff the fastest possible path from an idea to a shippable understanding product.",
        "question": "What do we want to teach today?",
        "why_exists": "Great teaching should start with intent, not paperwork. This department removes every step between wanting to teach something and having it manufactured.",
        "problems_solved": [
            "People waste time wiring together research, writing, and design by hand.",
            "Ideas die before they ever become products.",
            "There was no single front door for 'I want to teach X'.",
        ],
        "responsibilities": [
            "Accept a plain-language topic or teaching goal.",
            "Find or manufacture a verified Knowledge Record for it.",
            "Kick off the full package production line across every department.",
        ],
        "inputs": ["A topic or teaching goal in plain English", "Optional audience and product-package choice"],
        "outputs": ["A running manufacturing job", "A complete set of published, protected products"],
        "daily_activities": [
            "Receive teaching requests from the Founder.",
            "Route each request into the Workflow Engine.",
            "Report back what was produced.",
        ],
        "ai_agents": ["Production Line Conductor™", "Manufacturing Director™"],
        "people": ["Founder", "Executives", "Educators"],
        "related": ["Workflow Engine™", "Knowledge Records™", "Product Library"],
        "workflow": [
            "Type what you want to teach.",
            "System locates or builds a verified Knowledge Record.",
            "The full package line runs automatically.",
            "Finished products appear in the Library and Store.",
        ],
        "use_cases": [
            "'Teach how the human heart works' → complete book + video + poster package.",
            "A teacher requests a lesson bundle for a class next week.",
        ],
        "kpis": ["Time from idea to published product", "Packages launched per week", "Percentage that reach Treasure Standard™"],
        "treasure_standard": [
            "No product ships unless it is verified and Treasure Standard™ certified.",
            "Every launch is traceable back to a single teaching intent.",
        ],
        "future": ["Voice-command teaching requests", "Scheduled recurring curricula", "Team teaching queues"],
    },
    {
        "key": "workflows",
        "name": "Workflow Engine™",
        "route": "/workflows",
        "section": "The QRU Experience",
        "mission": "Coordinate every department required to manufacture understanding.",
        "purpose": "Act as the conductor that decides the correct order of work and runs departments in parallel.",
        "question": "What should happen next?",
        "why_exists": "Manufacturing a product touches many departments. Something must own the sequence, the hand-offs, and recovery when a step fails.",
        "problems_solved": [
            "Work stalled because no one owned the 'next step'.",
            "Departments ran out of order and produced defects.",
            "Failures halted the whole line instead of recovering.",
        ],
        "responsibilities": [
            "Run the governed 10-stage pipeline from Knowledge Record to Continuous Improvement.",
            "Manufacture multiple products in parallel with controlled concurrency.",
            "Recover automatically from errors and escalate only true exceptions.",
        ],
        "inputs": ["A verified Knowledge Record", "A chosen Workflow Template™"],
        "outputs": ["A tracked Workflow Job (WF-#####)", "Certified, published, distributed products"],
        "daily_activities": [
            "Launch and sequence manufacturing jobs.",
            "Retry failed product steps.",
            "Log every stage for full traceability.",
        ],
        "ai_agents": ["Workflow Orchestrator™", "Manufacturing Director™", "Recovery Agent™"],
        "people": ["Manufacturing Lead", "Founder (oversight)"],
        "related": ["Factory Monitor™", "Manufacturing Studio", "Verification Team™"],
        "workflow": [
            "Select a template and source record.",
            "Engine runs stages: Retrieve → Verify → Treasure Standard → Recipes → Parallel Manufacture → QC → Package → Distribute → Analytics → Improve.",
            "Each product self-certifies and publishes.",
        ],
        "use_cases": [
            "Run a Full Treasure Package™ end-to-end.",
            "Retry the two products that failed under load.",
        ],
        "kpis": ["Jobs completed per day", "Automation success rate", "Average products per job", "Founder-intervention rate"],
        "treasure_standard": [
            "Every stage is logged and reversible.",
            "No product publishes until it passes all release gates.",
        ],
        "future": ["Priority queues", "Cost-aware scheduling", "Cross-factory load balancing"],
    },
    {
        "key": "factory-monitor",
        "name": "Factory Monitor™",
        "route": "/factory-monitor",
        "section": "The QRU Experience",
        "mission": "Monitor every active production process in real time.",
        "purpose": "Show the live heartbeat of the factory so problems are seen the moment they appear.",
        "question": "What is happening right now?",
        "why_exists": "You cannot manage what you cannot see. The factory needs a live control-room view of all activity.",
        "problems_solved": [
            "No single place to see what the factory is doing this minute.",
            "Bottlenecks and escalations went unnoticed.",
            "Cost and quality were invisible during runs.",
        ],
        "responsibilities": [
            "Show jobs running, waiting, completed, and escalated.",
            "Surface division activity, AI usage, and estimated cost.",
            "Report quality, Treasure Standard™ compliance, and factory health.",
        ],
        "inputs": ["Live workflow job data", "Division and AI-usage telemetry"],
        "outputs": ["A real-time factory dashboard", "Health and cost signals"],
        "daily_activities": ["Watch active jobs", "Spot bottlenecks", "Confirm health is green"],
        "ai_agents": ["Factory Health Sentinel™"],
        "people": ["Founder", "Manufacturing Lead"],
        "related": ["Workflow Engine™", "Autonomy Center™", "Analytics"],
        "workflow": ["Open the monitor.", "Read live status.", "Drill into any job or escalation."],
        "use_cases": ["Confirm a batch is progressing.", "Catch a rate-limit spike as it happens."],
        "kpis": ["Live automation success", "Escalations open now", "Estimated production cost today"],
        "treasure_standard": ["Numbers shown are honest and live — never simulated when real data exists."],
        "future": ["Alert notifications", "Historical replay", "Anomaly detection"],
    },
    {
        "key": "autonomy",
        "name": "Autonomy Center™",
        "route": "/autonomy",
        "section": "The QRU Experience",
        "mission": "Make the factory smarter, safer, and more self-reliant every day.",
        "purpose": "Provide Level-5 autonomy: self-diagnostics, planning, and continuous improvement with minimal human input.",
        "question": "How do we get better and run ourselves?",
        "why_exists": "A world-class factory should detect its own problems, plan its own capacity, and recommend its own improvements.",
        "problems_solved": [
            "Issues were found by humans instead of the system.",
            "Improvement ideas were ad-hoc, not systematic.",
            "Capacity and cost planning were manual guesses.",
        ],
        "responsibilities": [
            "Run Self-Diagnostics™ and safe auto-repair.",
            "Produce the Executive Advisor™ daily brief and Factory Council™ report.",
            "Plan capacity, optimize cost, and detect knowledge gaps.",
        ],
        "inputs": ["Factory data and telemetry", "Product and quality history"],
        "outputs": ["Health scores", "Daily executive brief", "Improvement and capacity recommendations"],
        "daily_activities": ["Diagnose the factory", "Repair safe issues", "Recommend next moves"],
        "ai_agents": ["Executive Advisor™", "Factory Council™", "Cost Optimizer™", "Knowledge Gap Detector™"],
        "people": ["Founder", "Executives"],
        "related": ["Factory Monitor™", "Enterprise Health", "Analytics"],
        "workflow": ["Collect factory signals.", "Diagnose and score health.", "Auto-repair or recommend.", "Brief the Founder."],
        "use_cases": ["Get a morning brief on what to fix.", "See which knowledge topics are missing."],
        "kpis": ["Issues auto-resolved", "Improvement ideas acted on", "Forecast accuracy"],
        "treasure_standard": ["Auto-repairs are always safe and reversible.", "Recommendations degrade gracefully without the LLM."],
        "future": ["Predictive manufacturing", "Innovation radar", "Self-scaling capacity"],
    },
    {
        "key": "command-center",
        "name": "Enterprise Command Center™",
        "route": "/command-center",
        "section": "The QRU Experience",
        "mission": "Give the Founder one cross-division view of the entire enterprise.",
        "purpose": "Bring every operating division into a single command view with health, portfolio, and exceptions.",
        "question": "How is the whole enterprise doing?",
        "why_exists": "Leaders need one place that summarizes every division without opening ten dashboards.",
        "problems_solved": [
            "Enterprise status was scattered across many pages.",
            "Readiness and exceptions were hard to judge at a glance.",
        ],
        "responsibilities": [
            "Summarize the 6 operating divisions and their metrics.",
            "Show Enterprise Readiness Review™ and run the Factory Acceptance Test™.",
            "Highlight portfolio and open exceptions.",
        ],
        "inputs": ["Metrics from every division"],
        "outputs": ["Enterprise dashboard", "Readiness score", "FAT results"],
        "daily_activities": ["Review divisions", "Run readiness checks", "Clear exceptions"],
        "ai_agents": ["Enterprise Analyst™"],
        "people": ["Founder", "Executive Board"],
        "related": ["Founder Console", "Autonomy Center™", "Analytics"],
        "workflow": ["Open the center.", "Scan division health.", "Run FAT or readiness review as needed."],
        "use_cases": ["Judge if the enterprise is production-ready.", "Run a Factory Acceptance Test™."],
        "kpis": ["Enterprise Quality Score™", "Divisions green", "Open exceptions"],
        "treasure_standard": ["Readiness is scored honestly, including known gaps."],
        "future": ["Board-ready PDF exports", "Scenario planning"],
    },
    {
        "key": "governance",
        "name": "Governance Center™",
        "route": "/governance",
        "section": "The QRU Experience",
        "mission": "Hold the master governing documents that every department must obey.",
        "purpose": "Be the constitutional authority: the QRU Constitution, QBOS (visual), and QEDS (education) live here.",
        "question": "What rules govern everything we make?",
        "why_exists": "An enterprise needs a single, protected place for the laws, standards, and values that guide every decision.",
        "problems_solved": [
            "Standards were implied instead of written down.",
            "Different departments interpreted quality differently.",
        ],
        "responsibilities": [
            "Publish and version the QRU Constitution™, QBOS™, and QEDS™.",
            "Group division health against the standards.",
            "Feed standards into UI, tooltips, and AI prompts.",
        ],
        "inputs": ["Founder directives and standards"],
        "outputs": ["Published governing documents", "Compliance view"],
        "daily_activities": ["Read the standards", "Check division compliance"],
        "ai_agents": ["Constitution Keeper™"],
        "people": ["Founder", "All departments (as subjects)"],
        "related": ["Enterprise Blueprint™", "Verification Center™", "Creative Studio™"],
        "workflow": ["Open Governance.", "Review a governing document.", "Confirm divisions comply."],
        "use_cases": ["Read the QRU Constitution.", "Confirm a design follows QBOS."],
        "kpis": ["Documents current", "Divisions compliant"],
        "treasure_standard": ["Every product must trace to the Constitution, QBOS, and QEDS."],
        "future": ["Amendment history", "Automated compliance scoring"],
    },
    {
        "key": "blueprint",
        "name": "Enterprise Blueprint™",
        "route": "/blueprint",
        "section": "The QRU Experience",
        "mission": "Be the canonical Operations Manual that defines every QRU department.",
        "purpose": "Explain in plain English what every department owns, does, and why it exists — the One Question Test™ made visible.",
        "question": "What does every department do and why?",
        "why_exists": "Founders, employees, developers, educators, investors, and future AI agents all need one authoritative reference for how QRU works.",
        "problems_solved": [
            "Departments existed as features without clear missions.",
            "Onboarding and AI training had no single source of truth.",
            "No enforced standard for what makes a department valid.",
        ],
        "responsibilities": [
            "Hold a standardized Department Profile for every menu item.",
            "Enforce the One Question Test™ for any future department.",
            "Serve as the reference for onboarding, docs, and AI training.",
        ],
        "inputs": ["The department registry"],
        "outputs": ["Readable department profiles", "The official Operations Manual"],
        "daily_activities": ["Read a department profile", "Onboard a new person or agent"],
        "ai_agents": ["Enterprise Librarian™"],
        "people": ["Everyone at QRU", "Investors", "Future AI agents"],
        "related": ["Governance Center™", "every department"],
        "workflow": ["Open the Blueprint.", "Pick a department.", "Read its full profile."],
        "use_cases": ["Onboard a new employee.", "Train a new AI agent on the enterprise."],
        "kpis": ["Departments with a valid Primary Question", "Profiles kept current"],
        "treasure_standard": [
            "Every department must state one clear Primary Question or it is not yet defined.",
            "No jargon: written for founders, staff, developers, educators, and investors alike.",
        ],
        "future": ["Interactive org map", "Downloadable manual", "Versioned amendments"],
    },
    # ───────────────────────── MISSION CONTROL ─────────────────────────
    {
        "key": "dashboard",
        "name": "Founder Console",
        "route": "/",
        "section": "Mission Control",
        "mission": "Give the Founder a mission-first daily starting point.",
        "purpose": "Open the day with the executive briefing, Understanding Impact™, and enterprise health.",
        "question": "Where should the Founder focus today?",
        "why_exists": "The Founder needs a calm, mission-led home screen — impact first, business second.",
        "problems_solved": ["No clear daily starting point.", "Business metrics without mission context."],
        "responsibilities": [
            "Show the Daily Executive Briefing.",
            "Present Understanding Impact™ KPIs beside business metrics.",
            "Surface alerts, recommendations, and live activity.",
        ],
        "inputs": ["Enterprise metrics", "Impact data"],
        "outputs": ["Executive home dashboard"],
        "daily_activities": ["Read the brief", "Review impact", "Act on recommendations"],
        "ai_agents": ["Executive Advisor™"],
        "people": ["Founder"],
        "related": ["Enterprise Command Center™", "Autonomy Center™"],
        "workflow": ["Log in.", "Read the brief.", "Follow the top recommendation."],
        "use_cases": ["Start the day.", "Check lives-helped impact."],
        "kpis": ["People reached", "Lives helped", "Treasure products", "Enterprise health"],
        "treasure_standard": ["Impact is shown before revenue — mission first."],
        "future": ["Personalized founder goals", "Weekly reflection"],
    },
    {
        "key": "command",
        "name": "Command Console™",
        "route": "/command",
        "section": "Mission Control",
        "mission": "Let the Founder run the enterprise by talking to it.",
        "purpose": "Interpret natural-language commands and take the right action across the factory.",
        "question": "What do you want done — in your own words?",
        "why_exists": "The fastest interface is language. The Founder should command the factory conversationally.",
        "problems_solved": ["Clicking through many pages to do one thing.", "High learning curve for actions."],
        "responsibilities": [
            "Interpret plain-language commands.",
            "Create Knowledge Records, Manufacturing Orders, or run research automatically.",
            "Confirm what it did.",
        ],
        "inputs": ["A typed command"],
        "outputs": ["Executed actions", "Created records and orders"],
        "daily_activities": ["Accept commands", "Execute the right action", "Report results"],
        "ai_agents": ["Command Interpreter™"],
        "people": ["Founder", "Executives"],
        "related": ["Knowledge Records™", "Manufacturing Orders", "Research Center"],
        "workflow": ["Type a request.", "System interprets and acts.", "Result is confirmed."],
        "use_cases": ["'Research sleep science and start a record.'", "'Make a poster about hydration.'"],
        "kpis": ["Commands executed", "Success rate", "Actions saved vs manual clicks"],
        "treasure_standard": ["Every action is traceable and reversible."],
        "future": ["Voice commands", "Multi-step command plans"],
    },
    {
        "key": "enterprise-health",
        "name": "Enterprise Health",
        "route": "/enterprise-health",
        "section": "Mission Control",
        "mission": "Tell the truth about how healthy the enterprise is.",
        "purpose": "Break enterprise health into named systems with owners, causes, and next actions.",
        "question": "Is the enterprise healthy — and if not, why?",
        "why_exists": "Health must be transparent: not a single vague score, but explained system by system.",
        "problems_solved": ["Opaque 'all good' dashboards.", "No owner or fix for a weak area."],
        "responsibilities": [
            "Score ~10 named health systems.",
            "Explain why, who owns it, and the next action.",
            "Host the Enterprise Evolution Review™ and refactoring insights.",
        ],
        "inputs": ["Signals from every division"],
        "outputs": ["Transparent health breakdown", "Evolution recommendations"],
        "daily_activities": ["Review each system", "Assign fixes"],
        "ai_agents": ["Organizational Health Director™"],
        "people": ["Founder", "Executives"],
        "related": ["Autonomy Center™", "Governance Center™"],
        "workflow": ["Open health.", "Expand a weak system.", "Follow the recommended action."],
        "use_cases": ["Understand why a score dropped.", "Decide EXTEND vs CREATE for a new need."],
        "kpis": ["Systems green", "Time to resolve a weak system"],
        "treasure_standard": ["Health is explained honestly — no hidden red flags."],
        "future": ["Trend history", "Predictive health alerts"],
    },
    {
        "key": "organization",
        "name": "Organization",
        "route": "/organization",
        "section": "Mission Control",
        "mission": "Show who is on the team and what they are doing right now.",
        "purpose": "Maintain the Executive Board, Expertise Registry, and live organization activity.",
        "question": "Who is doing the work?",
        "why_exists": "An autonomous enterprise still needs a clear org: directors, specialists, workloads, and a live activity feed.",
        "problems_solved": ["No visibility into who owns what.", "No live sense of team activity."],
        "responsibilities": [
            "Maintain AI directors and Emergent specialists in the Expertise Registry™.",
            "Assemble the most qualified team per task.",
            "Stream live organization activity.",
        ],
        "inputs": ["Agent registry", "Task assignments"],
        "outputs": ["Org roster", "Assembled review teams", "Activity feed"],
        "daily_activities": ["Check workloads", "Assemble teams", "Read the activity feed"],
        "ai_agents": ["13 AI Directors", "13 Emergent Specialists"],
        "people": ["Founder", "Executive Board"],
        "related": ["Digital Workforce", "Workflow Engine™"],
        "workflow": ["Open Organization.", "See directors and specialists.", "Assemble a team for a task."],
        "use_cases": ["Assemble a review team.", "See who is busiest."],
        "kpis": ["Workload balance", "Availability", "Activity volume"],
        "treasure_standard": ["QRU extends specialists — it never replaces accountable ownership."],
        "future": ["Skill growth tracking", "Auto-balancing workloads"],
    },
    # ───────────────────────── KNOWLEDGE ─────────────────────────
    {
        "key": "knowledge",
        "name": "Knowledge Records™",
        "route": "/knowledge",
        "section": "Knowledge",
        "mission": "Store the verified understanding that powers every QRU product.",
        "purpose": "Be the master library of truth: research once, verify once, manufacture forever.",
        "question": "What do we know?",
        "why_exists": "Every product must trace back to a single, verified source of understanding.",
        "problems_solved": ["Duplicated research.", "Products built on unverified claims.", "Knowledge scattered and lost."],
        "responsibilities": [
            "Hold the full QRU teaching structure per topic (~46 fields).",
            "Track per-section status: Empty, Draft, Verified, Approved.",
            "Version records and flag dependent products when they change.",
        ],
        "inputs": ["Research findings", "Founder topics", "Verified evidence"],
        "outputs": ["Master Knowledge Records™", "The fields every product is assembled from"],
        "daily_activities": ["Create and edit records", "Fill missing sections", "Track versions"],
        "ai_agents": ["Knowledge Architect™", "Translation Engine™"],
        "people": ["Researchers", "Reviewers", "Founder"],
        "related": ["Verification Center™", "Translation Engine™", "Product Manufacturing"],
        "workflow": ["Create a record.", "Fill the teaching structure.", "Send to verification.", "Approve for manufacturing."],
        "use_cases": ["Author a record on the human heart.", "Update a record and see affected products."],
        "kpis": ["Verified records", "Sections verified vs draft", "Reuse across products"],
        "treasure_standard": ["Nothing is manufactured from unverified knowledge.", "Verified content is never overwritten silently."],
        "future": ["Automatic source refresh", "Knowledge graph links"],
    },
    {
        "key": "topic-registry",
        "name": "Topic Registry™",
        "route": "/topic-registry",
        "section": "Knowledge",
        "mission": "Keep a permanent, prioritized list of every topic QRU should teach.",
        "purpose": "Decide what to work on next based on public need and educational value.",
        "question": "What should we teach — and in what order?",
        "why_exists": "The enterprise needs a durable backlog of topics with permanent IDs and priority, not a scattered wish-list.",
        "problems_solved": ["No prioritized pipeline of topics.", "Lost or duplicated topic ideas."],
        "responsibilities": [
            "Assign permanent TOP-##### IDs.",
            "Score priority, public need, and educational value.",
            "Track manufacturing, verification, and Treasure status per topic.",
        ],
        "inputs": ["AI-generated topic ideas", "Founder priorities"],
        "outputs": ["A prioritized topic backlog", "Manufacturing Orders on import"],
        "daily_activities": ["Review topics", "Prioritize", "Import batches into production"],
        "ai_agents": ["Topic Scout™"],
        "people": ["Founder", "Executives"],
        "related": ["Bulk Orchestrator™", "Knowledge Records™", "Understanding Colleges"],
        "workflow": ["Generate or add topics.", "Score and prioritize.", "Import into manufacturing."],
        "use_cases": ["Plan a Health & Faith batch.", "Rank topics by public need."],
        "kpis": ["Topics registered", "Topics manufactured", "Priority accuracy"],
        "treasure_standard": ["Every product traces to a registered topic with a permanent ID."],
        "future": ["Demand signals from the Store", "Community topic requests"],
    },
    {
        "key": "translation-engine",
        "name": "Translation Engine™",
        "route": "/translation-engine",
        "section": "Knowledge",
        "mission": "Turn complex, technical truth into clear everyday understanding.",
        "purpose": "Convert any technical text into the full QRU teaching methodology — without dumbing it down.",
        "question": "How do we make this truly understandable?",
        "why_exists": "QRU does not simplify the truth; it simplifies the path to understanding it. That translation must have a home.",
        "problems_solved": ["Accurate content that no one can understand.", "Inconsistent explanation quality."],
        "responsibilities": [
            "Paste technical text → produce the full 11-part methodology.",
            "Fill only empty sections on a record; never overwrite verified content.",
            "Provide analogies, memory sentences, and everyday examples.",
        ],
        "inputs": ["Technical text", "A target Knowledge Record"],
        "outputs": ["Clear, structured understanding", "Filled record sections (Draft)"],
        "daily_activities": ["Translate technical passages", "Fill missing methodology sections"],
        "ai_agents": ["Translation Engine™", "Analogy Author™"],
        "people": ["Researchers", "Educators"],
        "related": ["Knowledge Records™", "Verification Center™", "Memory Engineering™"],
        "workflow": ["Paste text.", "Generate full methodology.", "Review and verify."],
        "use_cases": ["Translate a medical paper for a general reader.", "Create an analogy for a hard concept."],
        "kpis": ["Readability improvement", "Sections filled", "Verification pass rate"],
        "treasure_standard": ["Truth is preserved exactly; only the path is simplified."],
        "future": ["Multi-language translation", "Reading-level targeting"],
    },
    {
        "key": "research",
        "name": "Research Center",
        "route": "/research",
        "section": "Knowledge",
        "mission": "Gather and draft the raw understanding behind every topic.",
        "purpose": "Do the first-pass research that becomes a draft Knowledge Record.",
        "question": "What is the evidence?",
        "why_exists": "Before anything is verified or manufactured, someone must gather the facts and sources.",
        "problems_solved": ["Starting records from scratch.", "Missing sources and evidence."],
        "responsibilities": ["Run AI research on a topic.", "Draft a Knowledge Record.", "Collect sources and observed facts."],
        "inputs": ["A research topic"],
        "outputs": ["A draft Knowledge Record with sources"],
        "daily_activities": ["Research topics", "Draft records", "Attach evidence"],
        "ai_agents": ["Research Analyst™"],
        "people": ["Researchers"],
        "related": ["Knowledge Records™", "Verification Center™"],
        "workflow": ["Enter a topic.", "AI researches.", "Draft record is created."],
        "use_cases": ["Research a new health topic.", "Gather sources for a faith topic."],
        "kpis": ["Drafts produced", "Source quality", "Time to first draft"],
        "treasure_standard": ["Claims must carry evidence before moving forward."],
        "future": ["Live web sources", "Citation scoring"],
    },
    {
        "key": "verification",
        "name": "Verification Center™",
        "route": "/verification",
        "section": "Knowledge",
        "mission": "Ensure every published statement is accurate and evidence-based.",
        "purpose": "Be the gate where a reviewer approves, rejects, or requests revision on knowledge.",
        "question": "Can we trust it?",
        "why_exists": "Understanding is worthless if it is wrong. Verification protects QRU's credibility.",
        "problems_solved": ["Unverified claims reaching customers.", "No structured review of evidence."],
        "responsibilities": [
            "Evaluate evidence, sources, confidence, and conflicting evidence.",
            "Approve, reject, or request revision.",
            "Promote Draft sections to Verified; grant Treasure Standard™ where earned.",
        ],
        "inputs": ["Draft Knowledge Records"],
        "outputs": ["Verified records", "Verification decisions and logs"],
        "daily_activities": ["Review records", "Weigh evidence", "Approve or return"],
        "ai_agents": ["Kingdom Lion™ Verifier"],
        "people": ["Reviewers", "Founder (escalations)"],
        "related": ["Knowledge Records™", "Verification Team™", "Research Center"],
        "workflow": ["Open a record.", "Assess evidence.", "Approve / reject / request revision."],
        "use_cases": ["Verify a medical claim.", "Reject an unsupported statement."],
        "kpis": ["Records verified", "Rejection rate", "Time to verify"],
        "treasure_standard": ["Only evidence-based, verified statements are published."],
        "future": ["Automated source cross-checking", "Confidence scoring history"],
    },
    {
        "key": "verification-team",
        "name": "Verification Team™",
        "route": "/verification-team",
        "section": "Knowledge",
        "mission": "Verify knowledge automatically and escalate only true exceptions.",
        "purpose": "Provide AI-driven verification that reviews, revises, and re-verifies at scale.",
        "question": "Can we trust it — automatically, at scale?",
        "why_exists": "Human review cannot keep up with bulk manufacturing; trustworthy automation must handle the routine.",
        "problems_solved": ["Verification bottlenecks.", "Inconsistent review at scale."],
        "responsibilities": [
            "Review accuracy, clarity, completeness, and readability.",
            "Auto-revise weak sections and re-verify.",
            "Escalate to the Founder only on true exceptions.",
        ],
        "inputs": ["Records from bulk manufacturing"],
        "outputs": ["Auto-verified records", "Founder escalation queue"],
        "daily_activities": ["Auto-review records", "Revise and re-verify", "Escalate exceptions"],
        "ai_agents": ["AI Verification Team™"],
        "people": ["Founder (escalations only)"],
        "related": ["Verification Center™", "Bulk Orchestrator™"],
        "workflow": ["Receive a record.", "Score and revise.", "Auto-approve or escalate."],
        "use_cases": ["Verify a 25-topic batch hands-free.", "Escalate a conflicting-evidence case."],
        "kpis": ["Auto-approval rate", "Escalation rate", "Confidence threshold met"],
        "treasure_standard": ["Escalates on reject, conflicting evidence, human judgment, policy, or low confidence."],
        "future": ["Live confidence dashboards", "Self-tuning thresholds"],
    },
    {
        "key": "memory-engineering",
        "name": "Memory Engineering™",
        "route": "/memory-engineering",
        "section": "Knowledge",
        "mission": "Make verified understanding unforgettable.",
        "purpose": "Manufacture memory assets — hooks, chants, sentences, and character scripts — that make learning stick.",
        "question": "Will they remember it?",
        "why_exists": "Understanding that is forgotten changes nothing. Memory must be engineered on purpose.",
        "problems_solved": ["Content that is understood then forgotten.", "No systematic memory design."],
        "responsibilities": [
            "Create Memory Sentences™, hooks, chants, and call-and-response.",
            "Produce character voices and dialogue scripts.",
            "Attach memory assets to the Knowledge Record.",
        ],
        "inputs": ["A verified Knowledge Record"],
        "outputs": ["Memory assets stored on the record", "Learner-facing memory hooks"],
        "daily_activities": ["Craft memory hooks", "Design character scripts"],
        "ai_agents": ["6 Character Voices™", "Memory Designer™"],
        "people": ["Educators", "Creative team"],
        "related": ["Knowledge Records™", "Media Studio™", "Understanding Colleges"],
        "workflow": ["Pick a record.", "Generate memory assets.", "Surface hooks to learners."],
        "use_cases": ["Create a memory sentence for the water cycle.", "Write a character chant."],
        "kpis": ["Memory assets per record", "Learner recall (future)"],
        "treasure_standard": ["Never imitates real people; original QRU voices only."],
        "future": ["Spaced-repetition delivery", "Recall measurement"],
    },
    # ───────────────────────── MANUFACTURING ─────────────────────────
    {
        "key": "manufacturing",
        "name": "Manufacturing Orders",
        "route": "/manufacturing",
        "section": "Manufacturing",
        "mission": "Track each product build as a formal order moving through stages.",
        "purpose": "Give every manufacturing job a visible 6-stage Kanban from order to delivery.",
        "question": "What are we building right now, and at what stage?",
        "why_exists": "Work needs a formal order and a visible stage so nothing is lost between departments.",
        "problems_solved": ["Untracked work.", "No visibility into build stage."],
        "responsibilities": ["Create Manufacturing Orders™.", "Advance orders through 6 stages.", "Link orders to records and products."],
        "inputs": ["Approved Knowledge Records", "Product requests"],
        "outputs": ["Tracked orders", "Finished products"],
        "daily_activities": ["Create orders", "Advance stages", "Close completed orders"],
        "ai_agents": ["Manufacturing Coordinator™"],
        "people": ["Manufacturing Lead"],
        "related": ["Product Manufacturing", "Workflow Engine™"],
        "workflow": ["Create an order.", "Move it across the Kanban.", "Complete and deliver."],
        "use_cases": ["Track a book build.", "See which stage a poster is in."],
        "kpis": ["Orders completed", "Cycle time per stage"],
        "treasure_standard": ["No order skips a required stage."],
        "future": ["SLA timers", "Stage automation"],
    },
    {
        "key": "orchestrator",
        "name": "Bulk Orchestrator™",
        "route": "/orchestrator",
        "section": "Manufacturing",
        "mission": "Manufacture many topics at once, safely and hands-free.",
        "purpose": "Run large batches (25–50 topics) with queueing, pause/resume, and retry.",
        "question": "How do we scale production without breaking?",
        "why_exists": "Manufacturing one topic at a time cannot fill a library. Bulk production needs its own controller.",
        "problems_solved": ["Slow one-at-a-time production.", "No safe way to pause or retry batches."],
        "responsibilities": [
            "Batch topics and run them through research → KR → verify → QC → publish.",
            "Queue, pause, resume, and retry failed items.",
            "Estimate token cost and track progress and logs.",
        ],
        "inputs": ["Topic Registry batches"],
        "outputs": ["Published products at scale", "Batch progress and logs"],
        "daily_activities": ["Launch batches", "Retry failures", "Monitor progress"],
        "ai_agents": ["Orchestration Director™", "AI Verification Team™"],
        "people": ["Founder", "Manufacturing Lead"],
        "related": ["Topic Registry™", "Workflow Engine™", "Verification Team™"],
        "workflow": ["Import a batch.", "Launch.", "Retry any failures.", "Batch completes."],
        "use_cases": ["Manufacture a 10-topic Health & Faith batch.", "Resume a paused batch."],
        "kpis": ["Batch completion rate", "Cost per topic", "Retry success"],
        "treasure_standard": ["Batches pause gracefully on limits rather than burning failed jobs."],
        "future": ["Cost-capped batches", "Auto-scheduling overnight runs"],
    },
    {
        "key": "manufacture",
        "name": "Product Manufacturing",
        "route": "/manufacture",
        "section": "Manufacturing",
        "mission": "Turn a verified record into a full, finished product.",
        "purpose": "Generate complete product content across QRU's product types.",
        "question": "How do we make the actual product?",
        "why_exists": "Verified knowledge must become tangible products people can use.",
        "problems_solved": ["Knowledge that never becomes a product.", "Manual, inconsistent product writing."],
        "responsibilities": ["Generate full product content for 18+ product types.", "Feed products into the Library."],
        "inputs": ["A verified Knowledge Record", "A product type"],
        "outputs": ["A complete product (Markdown/assets)"],
        "daily_activities": ["Manufacture products", "Review output"],
        "ai_agents": ["Product Manufacturer™"],
        "people": ["Manufacturing team"],
        "related": ["Knowledge Records™", "Manufacturing Studio", "Product Library"],
        "workflow": ["Select record + type.", "Generate content.", "Send to studio/library."],
        "use_cases": ["Make a book from a record.", "Generate a lesson plan."],
        "kpis": ["Products manufactured", "First-pass quality"],
        "treasure_standard": ["Product content follows the 8-point QRU Thinking Model."],
        "future": ["More product types", "Template-driven assembly"],
    },
    {
        "key": "manufacturing-studio",
        "name": "Manufacturing Studio™",
        "route": "/manufacturing-studio",
        "section": "Manufacturing",
        "mission": "Assemble, quality-check, and certify products to Treasure Standard™.",
        "purpose": "Run the QC loop with live stages, release gates, and automatic improvement.",
        "question": "Is this product ready to ship?",
        "why_exists": "Products need a workshop where they are assembled, scored, improved, and gated before release.",
        "problems_solved": ["Products shipped before they were ready.", "No automatic quality improvement."],
        "responsibilities": [
            "Assemble products from verified fields (no regeneration).",
            "Score, route failing criteria to owning departments, auto-improve, and re-score.",
            "Enforce 8 release gates and certify Treasure Standard™.",
        ],
        "inputs": ["Manufactured products"],
        "outputs": ["Certified, gate-passed products"],
        "daily_activities": ["Run QC", "Watch stages and gates", "Certify products"],
        "ai_agents": ["QC Director™", "Improvement Loop™"],
        "people": ["Manufacturing Lead", "Reviewers"],
        "related": ["Product Manufacturing", "Creative Studio™", "Product Protection™"],
        "workflow": ["Assemble.", "Score & improve until standard is met.", "Pass gates → certify."],
        "use_cases": ["Certify a Treasure Standard™ product.", "Auto-fix a failing accessibility criterion."],
        "kpis": ["Certification rate", "QC rounds to pass", "Gate pass rate"],
        "treasure_standard": ["Release is LOCKED until every gate passes.", "Quality over speed."],
        "future": ["Gold Master comparisons", "Per-category benchmarks"],
    },
    {
        "key": "products",
        "name": "Product Library",
        "route": "/products",
        "section": "Manufacturing",
        "mission": "Hold every finished product QRU has made.",
        "purpose": "Be the catalog of manufactured products with publish, review, and archive controls.",
        "question": "What have we made?",
        "why_exists": "Finished products need a home where they can be found, reviewed, and published.",
        "problems_solved": ["Lost or scattered products.", "No lifecycle control over products."],
        "responsibilities": ["Store all products.", "Manage publish/review/archive.", "Show product detail and lineage."],
        "inputs": ["Certified products"],
        "outputs": ["A searchable product catalog"],
        "daily_activities": ["Browse products", "Publish or archive", "Open product detail"],
        "ai_agents": ["Catalog Manager™"],
        "people": ["Publishers", "Founder"],
        "related": ["Manufacturing Studio™", "QRU Store™", "Product Protection™"],
        "workflow": ["Open the library.", "Review a product.", "Publish or archive."],
        "use_cases": ["Find a published product.", "Archive an outdated product."],
        "kpis": ["Products published", "Catalog coverage by topic"],
        "treasure_standard": ["Products publish only after certification and protection."],
        "future": ["Collections", "Bulk lifecycle actions"],
    },
    {
        "key": "product-protection",
        "name": "Product Protection™",
        "route": "/product-protection",
        "section": "Manufacturing",
        "mission": "Protect QRU's products and control how they are licensed and accessed.",
        "purpose": "Verify products before publish and enforce licensing, copyright, and secure access.",
        "question": "Is it protected and properly licensed?",
        "why_exists": "Valuable products must be protected against misuse and licensed correctly for each audience.",
        "problems_solved": ["Unprotected products.", "No licensing or secure delivery."],
        "responsibilities": [
            "Run the AI product-verification gate before publish.",
            "Apply licenses (Personal/Classroom/School-Org/Commercial), copyright, and watermark flags.",
            "Provide account-gated access and expiring secure download links.",
        ],
        "inputs": ["Certified products"],
        "outputs": ["Protected, licensed, publish-ready products"],
        "daily_activities": ["Verify products", "Assign licenses", "Track access"],
        "ai_agents": ["Protection Agent™"],
        "people": ["Publishers", "Founder"],
        "related": ["Manufacturing Studio™", "Product Library", "Customers"],
        "workflow": ["Verify.", "License & watermark.", "Publish with secure access."],
        "use_cases": ["Publish with a Classroom license.", "Issue an expiring download link."],
        "kpis": ["Products protected", "License coverage", "Access compliance"],
        "treasure_standard": ["No product publishes without passing the protection gate."],
        "future": ["Usage analytics", "Automated takedown support"],
    },
    {
        "key": "creative-studio",
        "name": "Creative Studio™",
        "route": "/creative-studio",
        "section": "Manufacturing",
        "mission": "Transform verified understanding into beautiful, memorable learning experiences.",
        "purpose": "Own QRU's brand standards, creative briefs, and the creative publication gate.",
        "question": "Is it beautiful, engaging, and easy to understand?",
        "why_exists": "Truth deserves beauty. Products should look and feel worthy of the QRU name.",
        "problems_solved": ["Accurate but unattractive products.", "Inconsistent brand and creative quality."],
        "responsibilities": [
            "Maintain brand standards: color, typography, principles, QRU Shield™.",
            "Generate creative briefs per product page.",
            "Run a Creative Quality Review and gate publication.",
        ],
        "inputs": ["Manufactured products", "Brand standards"],
        "outputs": ["Branded creative direction", "Creative approval"],
        "daily_activities": ["Write briefs", "Review creative quality", "Approve for publish"],
        "ai_agents": ["Creative Studio Director™"],
        "people": ["Designers", "Creative reviewers"],
        "related": ["Design Intelligence™", "Media Studio™", "Governance Center™ (QBOS)"],
        "workflow": ["Brief the product.", "Review creative quality.", "Approve to publish."],
        "use_cases": ["Create a product-page brief.", "Block an off-brand product from publishing."],
        "kpis": ["Creative approval rate", "Brand consistency"],
        "treasure_standard": ["Products cannot publish until Creative-reviewed and on-brand (QBOS)."],
        "future": ["Live style previews", "Automated brand scoring"],
    },
    {
        "key": "media-studio",
        "name": "Media Studio™",
        "route": "/media-studio",
        "section": "Manufacturing",
        "mission": "Produce real voice, video, and visual media for QRU products.",
        "purpose": "Generate narration (OpenAI TTS) and slideshow videos (FFMPEG) plus branded imagery.",
        "question": "How do we bring it to life in sound and motion?",
        "why_exists": "Understanding reaches more people through audio and video, not just text.",
        "problems_solved": ["Text-only products.", "No real media production."],
        "responsibilities": ["Synthesize narration audio.", "Assemble branded slideshow videos.", "Manage media assets."],
        "inputs": ["Product scripts", "Scene images"],
        "outputs": ["MP3 narration", "MP4 videos", "Media assets"],
        "daily_activities": ["Render voice", "Assemble videos", "Store media"],
        "ai_agents": ["Media Producer™"],
        "people": ["Creative team"],
        "related": ["Creative Studio™", "Memory Engineering™", "AI Services™"],
        "workflow": ["Take a script.", "Synthesize voice.", "Render a video."],
        "use_cases": ["Narrate a lesson.", "Produce a short explainer video."],
        "kpis": ["Media assets produced", "Render success rate"],
        "treasure_standard": ["Media is real, not simulated, when a connector is available."],
        "future": ["Animation", "Licensed music", "Auto-captioning"],
    },
    {
        "key": "design-intelligence",
        "name": "Design Intelligence™",
        "route": "/design-intelligence",
        "section": "Manufacturing",
        "mission": "Learn from every great product so future products are even better.",
        "purpose": "Grow a Brand, Design, and Master Asset library and evolve QRU's Design Language™.",
        "question": "What does great QRU design look like — and how do we repeat it?",
        "why_exists": "Design quality should compound. Every Treasure Standard™ product should teach the system.",
        "problems_solved": ["Design knowledge lost after each product.", "No reusable design language."],
        "responsibilities": [
            "Maintain the Brand Library™, Design Library™, and Master Asset Library™.",
            "Extract design principles from certified products.",
            "Auto-recommend templates, palettes, and typography by product type.",
        ],
        "inputs": ["Certified Treasure Standard™ products"],
        "outputs": ["Design principles", "Template and palette recommendations"],
        "daily_activities": ["Learn from new products", "Recommend design choices"],
        "ai_agents": ["Design Intelligence™"],
        "people": ["Designers", "Creative Studio™"],
        "related": ["Creative Studio™", "Manufacturing Studio™", "Governance Center™ (QBOS)"],
        "workflow": ["Certify a product.", "Learn its design.", "Recommend for the next product."],
        "use_cases": ["Recommend a template for a health poster.", "Extract a new design principle."],
        "kpis": ["Principles learned", "Recommendation adoption"],
        "treasure_standard": ["Design language evolves only from certified, on-brand work."],
        "future": ["Gold Master design references", "Auto-layout generation"],
    },
    {
        "key": "experience-lab",
        "name": "Experience Lab™",
        "route": "/experience-lab",
        "section": "Manufacturing",
        "mission": "Judge how a product feels to a real learner before it ships.",
        "purpose": "Evaluate the end-to-end learner experience and surface friction.",
        "question": "How does this feel to learn?",
        "why_exists": "A product can be accurate and beautiful yet confusing to use. Experience must be tested.",
        "problems_solved": ["Shipping products that frustrate learners.", "No experience feedback loop."],
        "responsibilities": ["Evaluate learner experience.", "Score clarity and flow.", "Recommend improvements."],
        "inputs": ["A product and its learning flow"],
        "outputs": ["Experience evaluation and recommendations"],
        "daily_activities": ["Run experience evaluations", "Report friction"],
        "ai_agents": ["Experience Evaluator™"],
        "people": ["Product designers", "Educators"],
        "related": ["Creative Studio™", "Understanding Colleges", "Consumer Platform"],
        "workflow": ["Pick a product.", "Evaluate the experience.", "Recommend fixes."],
        "use_cases": ["Test a lesson's flow.", "Find where learners get stuck."],
        "kpis": ["Experience score", "Friction points resolved"],
        "treasure_standard": ["A product must be easy to learn, not just correct."],
        "future": ["Real learner testing", "A/B experience trials"],
    },
    # ───────────────────────── ENTERPRISE ─────────────────────────
    {
        "key": "workforce",
        "name": "Digital Workforce",
        "route": "/workforce",
        "section": "Enterprise",
        "mission": "Run the AI employees who actually do the manufacturing.",
        "purpose": "Define each Digital Employee's mission, permissions, tools, and metrics.",
        "question": "Who (which AI) does each job?",
        "why_exists": "An autonomous factory needs clearly defined AI workers with scope and accountability.",
        "problems_solved": ["Undefined AI responsibilities.", "No metrics on AI workers."],
        "responsibilities": ["Maintain AI Digital Employees.", "Set missions, permissions, and tools.", "Track performance metrics."],
        "inputs": ["Role definitions", "Task assignments"],
        "outputs": ["A defined AI workforce", "Per-employee metrics"],
        "daily_activities": ["Review AI workers", "Adjust permissions", "Check metrics"],
        "ai_agents": ["13 Digital Employees™"],
        "people": ["Founder", "Managers"],
        "related": ["Organization", "Workflow Engine™"],
        "workflow": ["Open a worker.", "Review its mission and metrics.", "Adjust scope."],
        "use_cases": ["Review the Research Analyst's output.", "Grant a tool to a worker."],
        "kpis": ["Worker output", "Task success rate", "Utilization"],
        "treasure_standard": ["Every AI worker has a clear mission and bounded permissions."],
        "future": ["Skill leveling", "Auto-hiring new specialists"],
    },
    {
        "key": "colleges",
        "name": "Understanding Colleges™",
        "route": "/colleges",
        "section": "Enterprise",
        "mission": "Organize understanding into subject divisions people can grow in.",
        "purpose": "Group topics and products into colleges (Health, Faith, and future divisions).",
        "question": "What subjects do we teach, and how deep?",
        "why_exists": "Knowledge needs structure by subject so learners and the factory can specialize.",
        "problems_solved": ["Unstructured subject areas.", "No home for divisional depth."],
        "responsibilities": ["Maintain colleges and their workspaces.", "Activate new divisions.", "Group topics and products by subject."],
        "inputs": ["Topics and products by subject"],
        "outputs": ["Subject colleges with workspaces"],
        "daily_activities": ["Manage colleges", "Activate divisions", "Curate subject content"],
        "ai_agents": ["College Deans™"],
        "people": ["Educators", "Founder"],
        "related": ["Topic Registry™", "Knowledge Records™", "Consumer Platform"],
        "workflow": ["Open a college.", "Curate its topics.", "Activate a new division."],
        "use_cases": ["Grow the Health college.", "Activate the Finance division."],
        "kpis": ["Active colleges", "Depth per college", "Learner enrollment"],
        "treasure_standard": ["Every college plugs into the same OS and standards."],
        "future": ["Trading, Finance, AI, Programming, Parenting, Business, Government divisions"],
    },
    {
        "key": "analytics",
        "name": "Analytics",
        "route": "/analytics",
        "section": "Enterprise",
        "mission": "Turn factory and market data into clear decisions.",
        "purpose": "Report knowledge growth, manufacturing, revenue, and impact.",
        "question": "What do the numbers tell us?",
        "why_exists": "Decisions must be grounded in evidence, not guesses.",
        "problems_solved": ["Decisions made on intuition.", "No trend visibility."],
        "responsibilities": ["Report KPIs and trends.", "Show revenue and impact.", "Feed the continuous-improvement loop."],
        "inputs": ["Factory, commerce, and impact data"],
        "outputs": ["Charts, KPIs, and reports"],
        "daily_activities": ["Review trends", "Report to leadership"],
        "ai_agents": ["Analytics Analyst™"],
        "people": ["Founder", "Executives"],
        "related": ["Command Center™", "Autonomy Center™", "QRU Store™"],
        "workflow": ["Open analytics.", "Read trends.", "Decide."],
        "use_cases": ["Track revenue growth.", "See which topics sell."],
        "kpis": ["Revenue", "Products sold", "Knowledge growth", "Impact reached"],
        "treasure_standard": ["Numbers are real and honest; synthetic data is labeled."],
        "future": ["Live cohorts", "Predictive forecasts"],
    },
    {
        "key": "customers",
        "name": "Customers",
        "route": "/customers",
        "section": "Enterprise",
        "mission": "Know and serve the people who learn with QRU.",
        "purpose": "Manage customer records, licensing, and relationships.",
        "question": "Who are we serving?",
        "why_exists": "Products exist for people; the enterprise must know and care for its customers.",
        "problems_solved": ["No view of who customers are.", "No licensing/relationship management."],
        "responsibilities": ["Maintain customer records.", "Manage licenses.", "Support relationships."],
        "inputs": ["Purchases and enrollments"],
        "outputs": ["Customer profiles", "License records"],
        "daily_activities": ["Review customers", "Manage licenses"],
        "ai_agents": ["Customer Advocate™"],
        "people": ["Support", "Founder"],
        "related": ["QRU Store™", "Product Protection™", "Consumer Platform"],
        "workflow": ["Open customers.", "Review a profile.", "Manage their license."],
        "use_cases": ["Look up a customer's licenses.", "Support a school account."],
        "kpis": ["Active customers", "Retention", "License coverage"],
        "treasure_standard": ["Customer delight is a measured outcome, not an afterthought."],
        "future": ["Customer library", "Loyalty and streaks"],
    },
    {
        "key": "store",
        "name": "QRU Store™",
        "route": "/store",
        "section": "Enterprise",
        "mission": "Sell QRU products and turn understanding into sustainable revenue.",
        "purpose": "Run the storefront and real Stripe checkout with honest revenue tracking.",
        "question": "How do people buy what we make?",
        "why_exists": "A self-sustaining enterprise needs real commerce to fund its mission.",
        "problems_solved": ["No way to purchase products.", "No real revenue tracking."],
        "responsibilities": [
            "Present the storefront with branded covers.",
            "Run real Stripe Checkout with a server-side price catalog.",
            "Fulfill purchases once and track revenue.",
        ],
        "inputs": ["Published, protected products", "Server-side price tiers"],
        "outputs": ["Completed purchases", "Revenue and sales data"],
        "daily_activities": ["Curate the storefront", "Process checkouts", "Track revenue"],
        "ai_agents": ["Commerce Director™"],
        "people": ["Founder", "Commerce team"],
        "related": ["Product Library", "Customers", "Analytics"],
        "workflow": ["Browse the store.", "Checkout via Stripe.", "Fulfillment and revenue recorded."],
        "use_cases": ["Sell a book.", "Track paid orders and AOV."],
        "kpis": ["Revenue", "Paid orders", "Average order value", "Conversion"],
        "treasure_standard": ["Prices are server-controlled; the client never sets amounts."],
        "future": ["Bundles", "Subscriptions", "Crypto checkout"],
    },
    # ───────────────────────── ADMINISTRATION ─────────────────────────
    {
        "key": "integration-hub",
        "name": "Integration Hub™",
        "route": "/integration-hub",
        "section": "Administration",
        "mission": "Connect QRU safely to the outside world.",
        "purpose": "Be the single source of truth for external platforms and credentials.",
        "question": "What are we connected to?",
        "why_exists": "The factory must publish and pay through many external services without leaking secrets.",
        "problems_solved": ["Scattered, unsafe credentials.", "No routing of products to platforms."],
        "responsibilities": [
            "Store encrypted credentials (never returned).",
            "Route product types to the right platforms.",
            "Monitor integrations with retry and escalation.",
        ],
        "inputs": ["Platform credentials", "Product distribution needs"],
        "outputs": ["Connected integrations", "Distribution routing"],
        "daily_activities": ["Connect platforms", "Monitor integrations"],
        "ai_agents": ["Integration Director™"],
        "people": ["Admins", "Founder"],
        "related": ["AI Services™", "QRU Store™", "Media Studio™"],
        "workflow": ["Add a connection.", "Route products.", "Monitor health."],
        "use_cases": ["Connect a payment provider.", "Route a book to a publishing platform."],
        "kpis": ["Active connections", "Distribution success rate"],
        "treasure_standard": ["Credentials are encrypted and never exposed."],
        "future": ["More live connectors", "Auto-reconnect"],
    },
    {
        "key": "ai-services",
        "name": "AI Services™",
        "route": "/ai-services",
        "section": "Administration",
        "mission": "Provide the AI capabilities the whole factory depends on.",
        "purpose": "Map each capability (text, image, media) to the connected service and run jobs.",
        "question": "What AI powers can we use right now?",
        "why_exists": "Every department relies on AI; those capabilities need one managed home.",
        "problems_solved": ["Unclear which AI powers are available.", "No AI job history or retry."],
        "responsibilities": ["Select the connected service per capability.", "Run AI jobs with history and retry.", "Estimate cost."],
        "inputs": ["AI job requests"],
        "outputs": ["AI results", "Job history and cost estimates"],
        "daily_activities": ["Run AI jobs", "Retry failures", "Track cost"],
        "ai_agents": ["AI Services Manager™"],
        "people": ["Admins", "Developers"],
        "related": ["Integration Hub™", "Media Studio™", "Product Manufacturing"],
        "workflow": ["Choose a capability.", "Run the job.", "Review results and cost."],
        "use_cases": ["Generate text.", "Render an image or voice."],
        "kpis": ["Job success rate", "Estimated cost", "Capability coverage"],
        "treasure_standard": ["Degrades gracefully when a limit is reached; never crashes the UI."],
        "future": ["Provider scorecards", "Auto-failover between providers"],
    },
    {
        "key": "users",
        "name": "User Management",
        "route": "/users",
        "section": "Administration",
        "mission": "Control who can access QRU and what they can do.",
        "purpose": "Manage accounts, roles, and permissions with the Founder as protected owner.",
        "question": "Who has access, and to what?",
        "why_exists": "Security and accountability require clear roles and protected ownership.",
        "problems_solved": ["Uncontrolled access.", "No role-based permissions."],
        "responsibilities": ["Manage users and roles (RBAC).", "Protect the Founder owner account.", "Enforce permissions."],
        "inputs": ["User accounts", "Role assignments"],
        "outputs": ["Managed, role-scoped accounts"],
        "daily_activities": ["Add/remove users", "Assign roles"],
        "ai_agents": ["Access Steward™"],
        "people": ["Admins", "Founder"],
        "related": ["Settings", "Governance Center™"],
        "workflow": ["Open users.", "Assign a role.", "Save."],
        "use_cases": ["Add a reviewer.", "Protect the owner account."],
        "kpis": ["Active users", "Role compliance"],
        "treasure_standard": ["The Founder owner is permanent and protected from deletion."],
        "future": ["Audit logs", "Granular permissions"],
    },
    {
        "key": "settings",
        "name": "Settings",
        "route": "/settings",
        "section": "Administration",
        "mission": "Configure how the QRU Factory runs.",
        "purpose": "Manage factory settings, security, and preferences.",
        "question": "How is the factory configured?",
        "why_exists": "Every enterprise needs one place to tune behavior and secure the account.",
        "problems_solved": ["Scattered configuration.", "No place to set a permanent password."],
        "responsibilities": ["Manage factory settings and preferences.", "Handle account security.", "Control hands-free mode."],
        "inputs": ["Configuration choices"],
        "outputs": ["Applied settings"],
        "daily_activities": ["Adjust settings", "Update security"],
        "ai_agents": ["Config Steward™"],
        "people": ["Founder", "Admins"],
        "related": ["User Management", "Autonomy Center™"],
        "workflow": ["Open settings.", "Change a preference.", "Save."],
        "use_cases": ["Set a permanent password.", "Toggle hands-free mode."],
        "kpis": ["Settings applied", "Security status"],
        "treasure_standard": ["Secure by default; nothing critical is hard-coded."],
        "future": ["Team preferences", "Environment profiles"],
    },
]

# Fast lookup by key
DEPARTMENTS_BY_KEY = {d["key"]: d for d in DEPARTMENTS}

# Sections in canonical order
SECTIONS = ["The QRU Experience", "Mission Control", "Knowledge", "Manufacturing", "Enterprise", "Administration"]

ONE_QUESTION_RULE = {
    "name": "The One Question Test™",
    "rule": "Every department must state ONE clear Primary Question. If its question cannot be stated clearly, the department is not yet sufficiently defined and must not be added to the platform.",
    "enforced_across": ["navigation", "tooltips", "onboarding", "dashboards", "documentation", "help screens", "future development"],
}


def get_departments():
    return DEPARTMENTS


def get_department(key: str):
    return DEPARTMENTS_BY_KEY.get(key)


def get_questions_map():
    """Lightweight key → {name, question, route} for nav tooltips."""
    return {d["key"]: {"name": d["name"], "question": d["question"], "route": d["route"]} for d in DEPARTMENTS}
